#' Simulated result data
#'
#' @description The simulated result data of only two sample types is generated by the functional PrioSubtypeDrug.
#'
#' @format A list containing 8 variables.
#'The variables are as follows:
#' \itemize{
#' 	\item Cacner Results table for cacner
#' 	\item SubpathwayMatrix Subpathway activity natrix
#' 	\item SampleInformation Cancer sample phenotypic information
#' 	\item Parameter Parameter of the function PrioSubtypeDrug
#' }
#' @examples
#' # data(Disease_drugs)
 "Disease_drugs"
