#' Simulation result data
#'
#' @description The result data of the simulation is generated by the functional OCSSD.
#'
#' @format A list containing 8 variables.
#'The variables are as follows:
#' \itemize{
#' 	\item Basal Results table for basal subtype
#' 	\item Her2 Results table for Her2 subtype
#' 	\item LumA Results table for LumA subtype
#' 	\item LumB Results table for LumB subtype
#' 	\item DrugMatrix Drug disease reverse association matrix
#' 	\item SubpathwayMatrix Subpathway activity natrix
#' 	\item SampleInformation Cancer sample phenotypic information
#' 	\item Parameter Parameter of the function OCSSD
#' }
#' @examples
#' # data(Subtype_drugs)
 "Subtype_drugs"
